// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA40o52RYyfZW3oNfyjKvQGxrd_UpKtJk8',
    appId: '1:815559639447:web:ab9e73c69b86753e4a84d2',
    messagingSenderId: '815559639447',
    projectId: 'flutter-1e2b6',
    authDomain: 'flutter-1e2b6.firebaseapp.com',
    storageBucket: 'flutter-1e2b6.appspot.com',
    measurementId: 'G-RXSV7GXV6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtk6KsjwSZ0WQXEsMSgA19h_cgKT3jyf8',
    appId: '1:815559639447:android:1b421d51db7dc2e34a84d2',
    messagingSenderId: '815559639447',
    projectId: 'flutter-1e2b6',
    storageBucket: 'flutter-1e2b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXrZCUllLceJqQNAb0aDba79cLwEUBh_w',
    appId: '1:815559639447:ios:6b5bbfcb540a1a9d4a84d2',
    messagingSenderId: '815559639447',
    projectId: 'flutter-1e2b6',
    storageBucket: 'flutter-1e2b6.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );
}
